bgwordaday/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('words.urls', namespace='words'))
]

words/urls.py
from django.urls import path
from . import views

app_name = 'words'

urlpatterns = [
    path('', views.todays_word, name='todays_word'),
    path('history', views.word_history, name='history'),
]

words/models.py
from django.db import models

# Create your models here.

class Word(models.Model):
    NOUN = 'n.'
    ADJECTIVE = 'adj.'
    VERB = 'v.'
    ADVERB = 'adv.'
    PARTS_OF_SPEECH_CHOICES = [
        (NOUN, 'Noun'),
        (ADJECTIVE, 'Adjective'),
        (VERB, 'Verb'),
        (ADVERB, 'Adverb')
    ]
    date = models.DateField()
    bgword = models.CharField(max_length=50, unique_for_date='date')
    partOfSpeech = models.CharField(
        max_length=9,
        choices=PARTS_OF_SPEECH_CHOICES,
        default=NOUN
    )
    transcript = models.CharField(max_length=75)
    definition = models.CharField(max_length=50)

    objects = models.Manager()

    class Meta:
        db_table = 'daily_words'

    def __str__(self):
        return self.transcript

words/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django import forms
from .models import Word
import datetime

# Create your views here.
def todays_word(request):

    today = datetime.date.today()
    word = Word.objects.get(date=today)
    subject = 'Your daily Bulgarian word!'
    message = f'The word for {today} is {word.bgword}, ({word.partOfSpeech}). \nIt is pronounced /{word.transcript}/ and its meaning is {word.definition}.'

    if request.method == 'POST':
        send_mail(subject, message, 'baldrianmockingjay@gmail.com', [request.POST.get('email')])

    return render(request,
                    'words/pages/index.html',
                    {'word': word})

def word_history(request):
    year = datetime.date.today().year
    month = datetime.date.today().month
    words_this_month = Word.objects.filter(date__year=year, date__month=month).order_by('-date')
    words_earlier = Word.objects.filter(date__year=year).exclude(date__month=month).order_by('-date')
    return render(request,
                    'words/pages/history.html',
                    {'words': words_this_month,
                    'label': words_this_month.first(),
                    'previous_words': words_earlier})

words/templates/words/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> {% block title %} {% endblock %} </title>
        <link rel="stylesheet" type="text/css" href="{% static 'words/css/style.css' %}">
        <!-- Fonts from Google -->
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,400;0,700;1,700&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Marmelad&display=swap" rel="stylesheet">
    </head>
    <body>
        <script src="{% static 'words/js/sidebar.js' %}"></script>
        <div id="sidebar">
            <div class="toggle-btn" onclick="toggleSidebar()">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <h3 class="entext">New Bulgarian word each day</h3>
            <a href="{% url 'words:todays_word' %}">Home</a>
            <a href="{% url 'words:history' %}">History</a>
            <a href="#">About</a>
            <div id="share">
                <form method="POST">
                    {% csrf_token %}
                    <input type="email" name="email" class="email">
                    <input type="submit" value="Share today's word by email" class="label">
                </form>
            </div>
        </div>

        <div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

words/templates/words/pages/history.html
{% extends "words/base.html" %}

{% block title %} Your New Bulgarian Word {% endblock %}

{% block content %}
<div id="wordtable">
    <h2 class="entext title">Word Archive</h2>
    <div style="display: block;">
        <h3 class="entext">{{label.date|date:'F Y'}}</h3>
        <div class="table-view">
            <table>
                {% for word in words %}
                <tr>
                    <td class="bgtext" style="font-size: 1.4em; text-align: left;">{{word.bgword}}</td>
                    <td class="right">/{{word.transcript}}/</td>
                    <td class="right">{{word.definition}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <h3 class="entext">Earlier this year</h3>
        <div class="table-view">
            <table>
                {% for word in previous_words %}
                <tr>
                    <td class="bgtext" style="font-size: 1.4em; text-align: left;">{{word.bgword}}</td>
                    <td class="right">/{{word.transcript}}/</td>
                    <td class="right">{{word.definition}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

words/templates/words/pages/index.html
{% extends "words/base.html" %}

{% block title %} Your New Bulgarian Word {% endblock %}

{% block content %}
<div id=content>
    <h1 class="bgtext">{{ word.bgword }}</h1>
    <p class="entext">/{{ word.transcript }}/</p>
    <p class="entext"><span style="font-size: 0.8em;"><em>{{ word.partOfSpeech }}</em></span>, {{ word.definition }}</p>
</div>
{% endblock %}